apiVersion: v1
kind: Service
metadata:
  name: assistmeaipms
spec:
  selector:
    app: assistmeaipms
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
